### ISSUE TITLE
Works pretty much out of the box...issue with application roots

### ISSUE THREAD

**Issue by exonome** [volkanpaksoy/voicemail-service-using-twilio#3]
Nice job first off to a simple approach to making a voicemail box for twilio phone. Worked pretty much immediately with the documentation available here. https://www.twilio.com/blog/build-a-voicemail-service-using-twilio-voice-and-aspdotnet-core

One issue that I could not solve. When deploying to the main application root of an IIS server, had no issues. When deploying to a virtual application/root, I could leave messages, but it always failed to retrieve them.  Tried multiple ways to reference the Voicemail folder within a virtual app folder, but no avail. It can get the count of files however.

**Comment by ghost** [comment]
Hi @exonome , I'm glad it (mostly) worked without much effort. Regarding your issue, I don't have an exact answer though, unfortunately. I'd have said mapping or permission issues. but getting the count of files correctly rules that out.

Basically, I'd check the path of the voicemails, which is set here: https://github.com/Dev-Power/voicemail-service-using-twilio/blob/1227e9dc419406fef4b5479a20578e008b48730f/src/VoicemailDirectory.WebApi/Services/FileService.cs#LL26C7-L26C7

Also make sure the files have mp3 extension as the code only selects those: https://github.com/Dev-Power/voicemail-service-using-twilio/blob/1227e9dc419406fef4b5479a20578e008b48730f/src/VoicemailDirectory.WebApi/Services/FileService.cs#LL26C7-L26C7

If you spot and fix a bug, I'd appreciate a PR so I would merge it to the main application and potentially update the Twilio article as well.

**Comment by ghost** [comment]
Also forgot to mention: Just this week published Part 2 of the article, which implements a Razor user interface to add more functionality: https://www.twilio.com/blog/build-a-voicemail-inbox-using-twilio-voice-and-blazor
